### PR TITLE
The readme text added.

### PR DESCRIPTION
**Pull request by ARiyou2000**

### CODE REVIEW

**Comment by jimsajimsa** [comment]
@ARiyou2000 tnx a lot, but plz add 3 line more:
- first: your name
- second: last name
- third: project's age!

**Comment by ARiyou2000** [comment]
new Update for Readme.

3 More Lines added.

**Comment by jimsajimsa** [comment]
It's a trouble! Be careful!

**Comment by ARiyou2000** [comment]
Dear @jimsajimsa thanks.

wrong lines fidex.

**Pull request merged**
